### ISSUE TITLE
Input box does not slide down (transition) unless the user clicks on the phone label

### ISSUE THREAD

**Issue by slalexander92** [timjongun/magicForm#1]
![screen shot 2016-11-04 at 10 28 45 am](https://cloud.githubusercontent.com/assets/16418650/20015661/85a012be-a279-11e6-8a56-3405ad418172.png)

Expected behavior: when the user clicks anywhere in the vicinity of the form input, the input should slide down to accommodate the input of text into the form.

Actual behavior:  User input overlaps the form label.  If the user clicks on the input itself, the input border doesn't slide down, but still allows the user to type words.

**Comment by timalanfarrow** [comment]
Whoops. Also, this will always happen if the input is focused before the page finishes loading.

**Comment by timalanfarrow** [comment]
Fixed. Sometimes if you call magicForm.init() twice it will open and then immediately close the input on focus.
